name: CI

on: [push, pull_request]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configurer PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '5.6.40'

      - name: Installer les dépendances
        run: composer install

      - name: Modifier les permissions de phpcs
        run: sudo chmod +x vendor/bin/phpcs

      - name: Modifier les permissions de phpunit
        run: sudo chmod +x vendor/bin/phpunit

      - name: Exécuter le linting
        run: php vendor/bin/phpcs --standard=PSR2 src

      - name: Exécuter les tests
        run: php vendor/bin/phpunit --bootstrap vendor/autoload.php tests
